import express from 'express';
import config from './config';
import path from 'path';
import serverRender from './renderers/serverRenderer';
import assets from '../public/assets.json';

const app = express();

app.use(express.static('public'));

app.set('views', path.join(__dirname, './', 'views'));

app.set('view engine', 'ejs');

app.get('/', (req, res) => {
  const { initialMarkup, preloadedState } = serverRender();

  /**
   * Function res.render: Sends data to index.ejx for rendering
   *
   * @param  {string} firstParam   .ejs file name to render
   * @param  {Object} secondParam  data to render index.ejs
   *   -title<string>:           app's title
   *   -initialMarkup<string>:   rendered react-redux app
   *   -preloadedState<Object>:  initial state from redux store
   *   -assets<json>:            assets hashed names generated by webpack
   */
  res.render('index', {
    title: 'MVST task',
    initialMarkup,
    preloadedState,
    assets,
  });
});

app.use((req, res) => {
  res.status(404).send('Sorry cant find that!<br><a href="/">go back</a>');
});

app.listen(config.port, () => {
  console.info(`Running on port ${config.port}...`);
});
